name: FTP deploy on push
on:
  push:
    branches:
    - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
      with:
        ftp-server: ${{ secrets.REMOTE_HOST }}
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        server-dir: test/
        local-dir: ./
