name: FTP deploy on push
on:
  push:
    branches:
    - master
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v3.1.2-patch
      with:
        server: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_PATH }}
